version: "3.9"
services:
  nft-home:
    container_name: home_exam
    image: httpd
    depends_on:
      - nft_db
    restart: always
    volumes:
      - ./nft-home:/usr/local/apache2/htdocs
    command: bash -c "npm install && npm run dev"
    ports:
      - "8081:80"

  nft_api:
    container_name: api_exam
    image: node:16
    depends_on:
      - nft_db
    restart: always
    volumes:
      - ./nft_api:/usr/src/app
    working_dir: /usr/src/app
    links:
      - "nft_db:db"
    command: bash -c "npm install && npm run nodemon"
    ports:
      - "8082:80"

  nft_db:
    image: mysql:5.6
    volumes:
      - ./nft_db/:/var/lib/mysql
    container_name: db_exam
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: firewall

    ports:
      - "3306:3306"
